"""add primary_doctor_id to admissions

Revision ID: 093268312883
Revises: 
Create Date: 2026-03-18 21:24:31.185426
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093268312883'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('primary_doctor_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_admissions_primary_doctor_id'), 'admissions', ['primary_doctor_id'], unique=False)
    op.create_foreign_key('fk_admission_primary_doctor_id', 'admissions', 'users', ['primary_doctor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_admission_primary_doctor_id', 'admissions', type_='foreignkey')
    op.drop_index(op.f('ix_admissions_primary_doctor_id'), table_name='admissions')
    op.drop_column('admissions', 'primary_doctor_id')
    # ### end Alembic commands ###
