"""Pydantic schemas for Contact Sales form submissions."""

from datetime import datetime

from pydantic import BaseModel, EmailStr, Field


class ContactSalesCreate(BaseModel):
    """Inbound schema matching the Figma 'Contact Sales' form fields."""

    first_name: str = Field(
        ..., min_length=1, max_length=100, examples=["Jane"]
    )
    last_name: str = Field(
        ..., min_length=1, max_length=100, examples=["Doe"]
    )
    work_email: EmailStr = Field(
        ..., examples=["jane.doe@hospital.ng"]
    )
    hospital_name: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Hospital or organization name",
        examples=["Lagos University Teaching Hospital"],
    )
    message: str = Field(
        ...,
        min_length=10,
        max_length=2000,
        description="How can we help?",
        examples=["We are interested in a product demo for our 200-bed facility."],
    )
    captcha_token: str = Field(
        ...,
        description="CAPTCHA token generated by the frontend (Cloudflare Turnstile or reCAPTCHA v3).",
    )


class ContactSalesOut(BaseModel):
    """Response schema returned after a successful submission."""

    id: str
    first_name: str
    last_name: str
    work_email: str
    hospital_name: str
    message: str
    created_at: datetime

    model_config = {"from_attributes": True}


class ContactSalesAck(BaseModel):
    """Lightweight acknowledgement returned to the frontend."""

    success: bool = True
    message: str = "Your request has been received. Our team will get back to you shortly."
